/* 
-COMANDOS DO SELECT-
select
from tabela
where condição
  and condição
   or condição
group by coluna
having condição
order by coluna asc desc
*/
USE DB_EXEMPLO;
-- FORMAS DE USAR O SELECT
SELECT CODIGO, NOME, CONTINENTE FROM PAIS;

SELECT * FROM PAIS;

SELECT CODIGO, NOME, CONTINENTE FROM PAIS
WHERE CONTINENTE = 'América do Sul';

SELECT CODIGO, NOME, CONTINENTE FROM PAIS
WHERE CONTINENTE = 'América do Sul'
OR CONTINENTE = 'Africa'
OR CONTINENTE = 'Asia';
/*
-CLAUSULA "IN" (DENTRO)-
*/
SELECT CODIGO, NOME, CONTINENTE FROM PAIS
WHERE CONTINENTE IN ('Asia', 'Africa', 'América do Sul');
/*
-CLAUSULA "NOT IN" (NÃO DENTRO)-
*/
SELECT CODIGO, NOME, CONTINENTE FROM PAIS
WHERE CONTINENTE NOT IN ('Asia', 'Africa', 'América do Sul')
ORDER BY CONTINENTE;
/* 
-FUNÇÕES AGREGADORAS-
SUM = SOMAR
COUNT = CONTAR
MAX = MAIOR VALOR
MIN = MENOR VALOR
AVG = MEDIA ARITMETICA
*/
SELECT COUNT(CODIGO) TOTAL_PAISES,
SUM(POPULACAO) SOMA_POPULACAO,
MAX(POPULACAO) MAIOR_POPULACAO,
MIN(POPULACAO) MENOR_POPULACAO,
AVG(POPULACAO) MEDIA_POPULACAO
FROM PAIS;
-- EXIBIR COUNT E SUM AGRUPADO POR CONTINENTE
SELECT CONTINENTE, COUNT(CODIGO) TOTAL_PAISES,
SUM(POPULACAO) SOMA_POPULACAO FROM PAIS
GROUP BY CONTINENTE;
/*
DESAFIO EXIBIR NOME DO PAIS COM MAIOR POPULACAO
DESAFIO EXIBIR NOME DO PAIS COM MENOR POPULACAO
*/
SELECT MAX(POPULACAO) FROM PAIS;
SELECT MIN(POPULACAO) FROM PAIS;
SELECT NOME, POPULACAO FROM PAIS
WHERE POPULACAO = (SELECT MAX(POPULACAO) FROM PAIS)
OR POPULACAO = (SELECT MIN(POPULACAO) FROM PAIS);
/*
-CLAUSULA "LIKE" TIPO-
BUSCA PADROES
*/
-- EXIBIR PAIS QUE COMECA COM "E"
SELECT NOME FROM PAIS
WHERE NOME LIKE 'B%';
-- EXIBIR PAIS QUE TERMINA COM "L"
SELECT NOME FROM PAIS
WHERE NOME LIKE '%L';
-- EXIBIR PAIS QUE COMECA COM "B" E TERMINA COM "L"
SELECT NOME FROM PAIS
WHERE NOME LIKE 'B%L';
-- EXIBIR PAIS QUE TENHA "CH" NO NOME
SELECT NOME FROM PAIS
WHERE NOME LIKE '%CH%';