DROP DATABASE IF EXISTS DB_EMPRESA ;
CREATE DATABASE DB_EMPRESA;
USE DB_EMPRESA;

CREATE TABLE TB_CARGO (  
	ID_CARGO INT NOT NULL PRIMARY KEY,  
	NM_CARGO VARCHAR(60) NOT NULL,  
    SALARIO DECIMAL(9,2) NOT NULL
);

CREATE TABLE TB_DEPARTAMENTO ( 
	ID_DEPARTAMENTO INT NOT NULL PRIMARY KEY,  
	NM_DEPARTAMENTO VARCHAR(40) NOT NULL
);

CREATE TABLE TB_EMPREGADO (  
	MATRICULA INT NOT NULL PRIMARY KEY,  
	NOME VARCHAR(80) NOT NULL,  
	DT_NASCIMENTO DATE NOT NULL,  
	SEXO CHAR(1) NOT NULL,  
	DT_ADMISSAO DATE NOT NULL,  
	FK_CARGO INT,  
	FK_DEPARTAMENTO INT,  
	FOREIGN KEY (FK_CARGO) REFERENCES TB_CARGO (ID_CARGO),  
	FOREIGN KEY (FK_DEPARTAMENTO) REFERENCES TB_DEPARTAMENTO (ID_DEPARTAMENTO)
);

INSERT INTO TB_CARGO (ID_CARGO, NM_CARGO, SALARIO) VALUES 
(1, 'Advogado', 9200.00),
(2, 'Administrador', 6500.00),
(3, 'Contador', 5600.00),
(4, 'Estagiário', 980.00),
(5, 'Gerente de Projeto', 8300.00),
(6, 'Programador', 7500.00),
(7, 'Administrador de Banco de Dados', 5990.00),
(8, 'Cientista de Dados', 8700.00),
(9, 'Secretária', 2200.00);

INSERT INTO TB_DEPARTAMENTO 
(ID_DEPARTAMENTO, NM_DEPARTAMENTO) VALUES
(100, 'Admistrativo'),
(200, 'Jurídico'),
(300, 'Contábil'),
(400, 'Tecnologia da Informação'),
(500, 'Recursos Humanos'),
(600, 'Comercial'),
(700, 'Financeiro');

INSERT INTO TB_EMPREGADO (MATRICULA, NOME, DT_NASCIMENTO, SEXO, 
DT_ADMISSAO, FK_CARGO, FK_DEPARTAMENTO) VALUES
(123, 'Vânia Alves', '1967-07-02', 'F', '2010-12-08', 2, 100),
(124, 'Florisbela Silva', '1999-10-02', 'F', '2019-10-01', 1, 200),
(125, 'Walter Amaral', '1998-02-02', 'M', '2018-05-25', 7, 400),
(126, 'Ana Cristina Peixoto', '1980-03-02', 'F', '2018-10-02', 4, 200),
(127, 'Clara Rodrigues', '1998-07-05', 'F', '2020-10-02', 4, 400),
(128, 'Flávio Luiz Silva', '1990-09-05', 'M', '2016-02-15', null, 400),
(129, 'Roberto Oliveira', '1981-03-10', 'M', '2012-12-10', 8, null),
(130, 'Cristina Moura', '1980-12-20', 'F', '2020-10-02', 9, 100),
(131, 'Gabriel Silva Costa', '1985-10-2', 'M', '2017-01-02', 3, null);

SELECT * FROM TB_CARGO;
SELECT * FROM TB_DEPARTAMENTO;
SELECT * FROM TB_EMPREGADO;

-- SELECT DE DUAS TABELAS UNIDAS
SELECT MATRICULA, NOME, NM_CARGO, SALARIO 
FROM TB_EMPREGADO INNER JOIN TB_CARGO
ON ID_CARGO = FK_CARGO;

-- NOME DO EMPREGADO DATA DE ADMISSAO E NOME DO DEPARTAMENTO
SELECT NOME, DT_ADMISSAO, NM_DEPARTAMENTO
FROM TB_EMPREGADO INNER JOIN TB_DEPARTAMENTO
ON FK_DEPARTAMENTO = ID_DEPARTAMENTO;

/* 
	DESAFIO:
    SELECIONE MATRICULA, NOME, DT_NASCIMENTO, CARGO DO EMPREGADO,
    SALARIO E O DEPARTAMENTO ONDE ELE TRABALHO
*/

SELECT MATRICULA, NOME, DT_NASCIMENTO AS BIRTHDAY, 
NM_CARGO AS CARGO, SALARIO, NM_DEPARTAMENTO AS DEPARTAMENTO
FROM TB_EMPREGADO INNER JOIN TB_CARGO
ON FK_CARGO = ID_CARGO INNER JOIN TB_DEPARTAMENTO
ON FK_DEPARTAMENTO = ID_DEPARTAMENTO ORDER BY NOME;

-- JUNÇÃO INTERNA
SELECT * FROM TB_EMPREGADO
INNER JOIN TB_CARGO ON ID_CARGO = FK_CARGO;

-- JUNÇÃO A ESQUERDA
SELECT * FROM TB_EMPREGADO
LEFT JOIN TB_CARGO ON ID_CARGO = FK_CARGO;

-- JUNÇÃO A DIREITA
SELECT * FROM TB_EMPREGADO
RIGHT JOIN TB_CARGO ON ID_CARGO = FK_CARGO;

/*
	1 - Selecione nome do empregado, cargo e salario, dos empregados que trabalham no 
	departamento Tecnologia da Informação
    
    2 - Selecione o nome dos empregados e departamentos dos empregados que são estagiarios
	e não trabalham da Tecnologia da Informação
    
    3 - Selecione a contagem de quantos empregados tem trabalhando em cada departamento,
	departamentos com nenhum empregado deverá apresentar a contagem 0
    
    4 - Selecione a contagem de quantos empregados tem por cargo
    
    5 - Selecione a soma dos salarios dos empregados por departamento
*/

-- 1
SELECT NOME, NM_CARGO AS CARGO, SALARIO, 
NM_DEPARTAMENTO AS DEPARTAMENTO FROM TB_EMPREGADO 
INNER JOIN TB_CARGO ON FK_CARGO = ID_CARGO 
INNER JOIN TB_DEPARTAMENTO ON FK_DEPARTAMENTO = ID_DEPARTAMENTO 
WHERE NM_DEPARTAMENTO = 'Tecnologia da Informação'
ORDER BY NOME;

-- 2
SELECT NOME, NM_DEPARTAMENTO AS DEPARTAMENTO, NM_CARGO AS CARGO FROM TB_EMPREGADO 
INNER JOIN TB_DEPARTAMENTO ON FK_DEPARTAMENTO = ID_DEPARTAMENTO 
INNER JOIN TB_CARGO ON FK_CARGO = ID_CARGO
WHERE NM_CARGO = 'Estagiário'
AND NM_DEPARTAMENTO <> 'Tecnologia da Informação';

-- 3
SELECT NM_DEPARTAMENTO AS DEPARTAMENTO, COUNT(MATRICULA) TOTAL_EMPREGADOS
FROM TB_DEPARTAMENTO LEFT JOIN TB_EMPREGADO
ON FK_DEPARTAMENTO = ID_DEPARTAMENTO
GROUP BY NM_DEPARTAMENTO ORDER BY TOTAL_EMPREGADOS DESC;

-- 4
SELECT NM_CARGO AS CARGO, COUNT(MATRICULA) TOTAL_EMPREGADOS
FROM TB_EMPREGADO RIGHT JOIN TB_CARGO
ON FK_CARGO = ID_CARGO
GROUP BY NM_CARGO ORDER BY TOTAL_EMPREGADOS DESC;

-- 5
SELECT NM_DEPARTAMENTO AS DEPARTAMENTO, SUM(SALARIO) AS SOMA_SALARIOS
FROM TB_DEPARTAMENTO LEFT JOIN TB_EMPREGADO 
ON FK_DEPARTAMENTO = ID_DEPARTAMENTO LEFT JOIN TB_CARGO
ON FK_CARGO = ID_CARGO
GROUP BY NM_DEPARTAMENTO;