// Estruturas condicionais parte 1
package Curso_Guanabara.Class;
// @author Cauã Sousa
import java.util.Scanner;
import java.time.LocalDate;
public class Aula09 {
    public static void main(String[] args) {
        AulaTeorica09.main(args);
        AulaPratica09.main(args);
    }
}
class AulaTeorica09 {
    public static void main(String[] args) {
        Scanner scAula09 = new Scanner(System.in);

        System.out.println("Vamos recriar o exemplo da Print desta aula!");
        System.out.println("Aperte ENTER para proximo exemplo.");
        scAula09.nextLine();

        float n1, n2, media;

        System.out.print("Olá, aluno! Digite o valor da sua nota na PRIMEIRA prova: ");
        n1 = scAula09.nextFloat();
        System.out.print("Olá, aluno! Digite o valor da sua nota na SEGUNDA prova: ");
        n2 = scAula09.nextFloat();

        media = (n1 + n2) / 2;
        System.out.println();

        if (media > 9) {
            System.out.print("Parabéns! ");
        }
        System.out.printf("Sua média é %.1f \n", media);

        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula09.nextLine();
        scAula09.nextLine();

        // NEXT

        int anoAtual = LocalDate.now().getYear();
        int anoNasc, idade;

        System.out.print("Digite o ano de seu nascimento: ");
        anoNasc = scAula09.nextInt();

        idade = anoAtual - anoNasc;
        System.out.println();

        if (idade >= 18) {
            System.out.println("Você é maior de Idade!");
        } else {
            System.out.println("De menor!");
        }

        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula09.nextLine();
        scAula09.nextLine();

        // NEXT

        scAula09.close();
    }
}
class AulaPratica09 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AulaPratica09.class.getName());

    /**
     * Creates new form AulaPratica09
     */
    public AulaPratica09() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnVerificar = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Valor");

        txtValor.addActionListener(this::txtValorActionPerformed);

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(this::btnVerificarActionPerformed);

        lblResultado.setText("Par ou Impar?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVerificar, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVerificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void txtValorActionPerformed(java.awt.event.ActionEvent evt) {                                         
    }                                        

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int valor = Integer.parseInt(txtValor.getText());

        if (valor % 2 == 0) {
            lblResultado.setText("É PAR!!");
        } else {
            lblResultado.setText("É IMPAR!!");
        }
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AulaPratica09().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnVerificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtValor;
    // End of variables declaration                   
}