// Estruturas condicionais parte 2
package Curso_Guanabara.Class;
// @author Cauã Sousa
import java.util.Scanner;
import java.time.LocalDate;
public class Aula10 {
    public static void main(String[] args) {
        Scanner scAula10 = new Scanner(System.in);
        AulaTeorica10.main(scAula10);
        AulaPratica10.main(args);
        AulaTeorica10pt2.main(scAula10);
        scAula10.close();
    }
}
class AulaTeorica10 {
    public static void main(Scanner scAula10) {
        System.out.println("Vamos recriar o exemplo da Print desta aula!");
        System.out.println("Aperte ENTER para proximo exemplo.");
        scAula10.nextLine();

        int nasc, i, anoAtual = LocalDate.now().getYear();

        System.out.print("Digite o ano de seu nascimento: ");
        nasc = scAula10.nextInt();

        i = anoAtual - nasc;

        if (i < 16) {
            System.out.println("NÃO VOTA!");
        } else if (i >= 16 && i < 18 || (i > 70)) {
            System.out.println("VOTO OPICIONAL");
        } else {
            System.out.println("VOTO OBRIGATORIO!");
        }
        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula10.nextLine();
        scAula10.nextLine();
    }
}
class AulaPratica10 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AulaPratica10.class.getName());

    /**
     * Creates new form AulaPratica10
     */
    public AulaPratica10() {
        initComponents();
        lblResultado.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        btnVoto = new javax.swing.JButton();
        lblResultado = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblIdade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ano de Nascimento");

        btnVoto.setText("Posso votar?");
        btnVoto.addActionListener(this::btnVotoActionPerformed);

        lblResultado.setText("0");

        jLabel2.setText("Resultado:");

        lblIdade.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(btnVoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblIdade)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultado)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnVotoActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int nasc, i, anoAtual = LocalDate.now().getYear();

        nasc = Integer.parseInt(txtAno.getText());
        i = anoAtual - nasc;

        if (i < 16) {
            lblResultado.setText("NÃO VOTA!");
            lblIdade.setText(Integer.toString(i) + " Anos");
        } else if (i >= 16 && i < 18 || (i > 70)) {
            lblResultado.setText("VOTO OPCIONAL");
            lblIdade.setText(Integer.toString(i) + " Anos");
        } else {
            lblResultado.setText("VOTO OBRIGATORIO!");
            lblIdade.setText(Integer.toString(i) + " Anos");
        }
        lblResultado.setVisible(true);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AulaPratica10().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnVoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtAno;
    // End of variables declaration                   
}
class AulaTeorica10pt2 {
    public static void main(Scanner scAula10) {

        int pernas; String tipo;

        System.out.print("Digite a quantidade de pernas: ");
        pernas = scAula10.nextInt();

        switch (pernas) {
            case 1:
                tipo = "Saci";
                break;
            case 2:
                tipo = "Bipede";
                break;
            case 4:
                tipo = "Quadrupede";
                break;
            case 6, 8:
                tipo = "Aranha";
                break;
            default:
                tipo = "ET";
                break;
        }
        System.out.println("Você é " + tipo);
        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula10.nextLine();
        scAula10.nextLine();
    }
}