// Estruturas de Repetição (Parte 1)
package Curso_Guanabara.Class;
// @author Cauã Sousa
import java.util.Scanner;
public class Aula11 {
    public static void main(String[] args) {
        Scanner scAula11 = new Scanner(System.in);
        AulaTeorica11.executar(scAula11);
        AulaPratica11.main(args);
        scAula11.close();
    }
}
class AulaTeorica11 {
    public static void executar(Scanner scAula11) {
        System.out.println("Podemos aplicar as prints da aula de duas formas, para 1º forma, aperte ENTER:");
        scAula11.nextLine();

        int cc = 0;
        while (cc < 4) {
            System.out.println("Deu cambalhota!");
            cc++;
        }

        System.out.println("\nPara 2º forma, aperte ENTER:");
        scAula11.nextLine();

        for (int i = 0; i < 4; i++) {
            System.out.println("Deu cambalhota!");
        }

        System.out.println("\nENTER para continuar!");
        scAula11.nextLine();

        System.out.println("Pode se usar qualquer um dos dois para tudo, mas se tivesse uma regra...");
        System.out.println("Se tem contador/controlado > usa for");
        System.out.println("Se é condição aberta/incerta > usa while");

        System.out.println("\nENTER para continuar!");
        scAula11.nextLine();

        for (int i = 1; i < 5; i++) {
            System.out.println("Cambalhota de número " + i);
        }

        System.out.println("\nAgora vamos para o comando \"continue\":");
        System.out.println("ENTER para continuar!");
        scAula11.nextLine();

        int cont = 0;
        while (cont < 10) {
            cont++;
            if ((cont % 2) == 0) {
                System.out.println("Cambalhota de número " + cont);
            } else {
                continue;
            }
        }

        System.out.println("\nEssa foi com while, agora com for:");
        System.out.println("ENTER para continuar!");
        scAula11.nextLine();

        for (int i = 1; i <= 10; i++) {
            if ((i % 2) == 0) {
                System.out.println("Cambalhota de número " + i);
            } else {
                continue;
            }
        }

        System.out.println("\nExiste também o Break, que também interrompe laço como o continue. Mas dessa vez " +
        "parando completamente o laço!");
        System.out.println("ENTER para continuar!");
        scAula11.nextLine();

        for (int i = 1; i <=10; i++) {
            if (i <= 7) {
                System.out.println("Cambalhota de núemro " + i);
            } else {
                System.out.println("\nA cambalhota falhou, e o acrobata se machucou! :/");
                break;
            }
        }

        System.out.println("\nFim da parta teorica, hora da janela!");
        System.out.println("ENTER para continuar!");
        scAula11.nextLine();
    }
    public static void main(String[] args) {
        Scanner scAula11 = new Scanner(System.in);
        executar(scAula11);
        scAula11.close();
    }
}
class AulaPratica11 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AulaPratica11.class.getName());

    /**
     * Creates new form AulaPratica11
     */
    public AulaPratica11() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblContagem = new javax.swing.JLabel();
        btnContar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Contagem:");

        lblContagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContagem.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnContar.setText("Contar");
        btnContar.addActionListener(this::btnContarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnContar, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblContagem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblContagem, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnContar)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>                        

    private void btnContarActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int cc = 0;
        String contagem = "";
        
        while (cc < 5) {
            contagem += cc + " ";
            cc++;
        }
        lblContagem.setText(contagem);
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AulaPratica11().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnContar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblContagem;
    // End of variables declaration                   
}
