// Operador Ternário
package Curso_Guanabara.Class;
// @author Cauã Sousa
import java.util.Scanner;
public class Aula08 {
    public static void main(String[] args) {
        AulaTeorica08.main(args);
        AulaPratica08.main(args);
    }
}
class AulaTeorica08 {
    public static void main(String[] args) {
        Scanner scAula08 = new Scanner(System.in);

        int n1, n2, r;
        n1 = 4;
        n2 = 8;

        r = (n1>n2)?0:1;

        System.out.println(r);

        // Vai retornar 1 pois n2 é maior

        n1 = 12;
        n2 = 8;

        r = (n1>n2)?n1:n2;

        System.out.println(r);

        // Vai retornar 12, pois n1 (12) é maior que n2 (8)

        n1 = 14;
        n2 = 18;

        r = (n1>n2)?n1+n2:n1-n2;

        System.out.println(r);

        // Vai retornar -4, n2 é maior, logo 14 - 18 que é = -4
        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula08.nextLine();

        System.out.println("Maior que >");
        System.out.println("Menor que <");
        System.out.println("Maior ou igual >=");
        System.out.println("Menor ou igual <=");
        System.out.println("Igual ==");
        System.out.println("Diferente !=");

        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula08.nextLine();

        String nome1 = "Gustavo";
        String nome2 = "Gustavo";
        String nome3 = new String("Gustavo");
        String resultado;

        resultado = (nome1==nome2)?"Iguais":"Diferentes";
        System.out.println(resultado);

        // Retorna Iguais, as estruturas e o nome são os mesmos

        resultado = (nome1==nome3)?"Iguais":"Diferentes";
        System.out.println(resultado);

        // Retorna Diferentes, as estruturas não são as mesmas, apesar do nome ser

        resultado = (nome1.equals(nome3))?"Iguais":"Diferentes";
        System.out.println(resultado);

        // Retorna Iguais, o metodo .equals compara o CONTEUDO dentro da String
        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula08.nextLine();

        System.out.println("&& para \"e\": Verdadeiro && Falso = Falso");
        System.out.println("|| para \"ou\": Verdadeiro || Falso = Verdadeiro");
        System.out.println("^ para \"ou exclusivo\": Verdadeiro ^ Verdadeiro = Falso");
        System.out.println("! para \"não\": !Falso = Verdadeiro");

        System.out.println("\nAperte ENTER para proximo exemplo.");
        scAula08.nextLine();
        scAula08.close();
    }
}
class AulaPratica08 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AulaPratica08.class.getName());

    /**
     * Creates new form AulaPratica08
     */
    public AulaPratica08() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAno = new javax.swing.JTextField();
        btnCalc = new javax.swing.JButton();
        lblIdade = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ano de Nascimento");

        jLabel2.setText("Idade");

        jLabel3.setText("Situação");

        btnCalc.setText("Calcular Idade");
        btnCalc.addActionListener(this::btnCalcActionPerformed);

        lblIdade.setText("0");

        lblSituacao.setText("<vazio>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCalc))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSituacao)
                            .addComponent(lblIdade))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblIdade))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(lblSituacao))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int ano = Integer.parseInt(txtAno.getText());
        int idade = 2026 - ano;
        lblIdade.setText(Integer.toString(idade));

        String sit = (idade < 16)?"NÃO VOTA":((idade >= 16 && idade < 18) || (idade > 70)) ? "VOTO OPCIONAL":"VOTO OBRIGATORIO!";
        lblSituacao.setText(sit);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AulaPratica08().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblIdade;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JTextField txtAno;
    // End of variables declaration                   
}