// Declaração de Variavel
package Curso_Guanabara.Class;
// @author Cauã Sousa
import java.util.Scanner;
public class Aula06 {
    public static void main(String[] args) {
        AulaTeorica06.main(args);
        AulaPratica06.main(args);
    }
}
class AulaTeorica06 {
    @SuppressWarnings("resource")
    public static void main(String[] args) {
        Scanner scAula06Gn = new Scanner(System.in);

        int exemploIdade = 3; // Variavel
        int exemploIdade2 = (int) 3; // Typecast - Variavel
        @SuppressWarnings("removal")
        Integer exemploIdade3 = new Integer(3); // Wrapper Class - Objeto

        float exemploSalario = 1825.54f; // Variavel
        float exemploSalario2 = (float) 1825.54; // Typecast - Variavel
        @SuppressWarnings("removal")
        Float exemploSalario3 = new Float(1825.54); // Wrapper Class - Objeto

        char exemploLetra = 'G';
        char exemploLetra2 = (char) 'G';
        @SuppressWarnings("removal")
        Character exemploLetra3 = new Character('G');

        boolean exemploCasado = false;
        boolean exemploCasado2 = (boolean) false;
        @SuppressWarnings("removal")
        Boolean exemploCasado3 = new Boolean(false);

        System.out.println("Existem diversas maneiras de declarar a mesma variavel. Exemplo int:");
        System.out.println("int idade = 3; int idade = (int) 3; Integer idade = new Integer(3);");
        System.out.println("A palavra \"new\" sempre cria um novo \"Objeto\".");
        System.out.println("No codigo, um exemplo de cada foi feito, as diferenças estão comentadas no código. "
        + "Aperte enter para exibir os resultados");
        scAula06Gn.nextLine();

        System.out.println(exemploIdade);
        System.out.println(exemploIdade2);
        System.out.println(exemploIdade3);
        scAula06Gn.nextLine();

        System.out.println("A seguir, vamos sair dos numeros inteiros e ver outros exemplos. Siga apertando Enter até "
        + "terminar de ver todos os exemplos.");
        scAula06Gn.nextLine();

        System.out.printf("%.2f \n", exemploSalario);
        System.out.printf("%.2f %n", exemploSalario2);
        System.out.format("%.2f %n", exemploSalario3);
        scAula06Gn.nextLine();

        System.out.println(exemploLetra);
        System.out.println(exemploLetra2);
        System.out.println(exemploLetra3);
        scAula06Gn.nextLine();

        System.out.println(exemploCasado);
        System.out.println(exemploCasado2);
        System.out.println(exemploCasado3);
        scAula06Gn.nextLine();

        System.out.println("É possivel converter objetos, exemplo de \"int\" para \"String\": Integer.toString.");
        System.out.println("Abaixo, um print de String que era int");
        scAula06Gn.nextLine();

        int exemploIdade4 = 21;
        String idadeToString = Integer.toString(exemploIdade4);

        System.out.println(idadeToString);
        scAula06Gn.nextLine();

        System.out.println("O oposto pode ser feito com Integer.perseInt ou Float.perseFloat em números reais Segue exemplos:");
        scAula06Gn.nextLine();

        String exemploIdade5 = "21";
        int idadePerseInt = Integer.parseInt(exemploIdade5);

        String exemploIdade6 = "21.5";
        float idadePerseFloat = Float.parseFloat(exemploIdade6);

        System.out.println(idadePerseInt);
        System.out.printf("%.1f", idadePerseFloat);
        scAula06Gn.nextLine();
    }
}
/**
 *
 * @author Cauã Sousa
 */
class AulaPratica06 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AulaPratica06.class.getName());

    /**
     * Creates new form AulaPratica06
     */
    public AulaPratica06() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        txtN1 = new javax.swing.JTextField();
        txtN2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblSoma = new javax.swing.JLabel();
        btnSoma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("+");

        lblSoma.setText("0");

        btnSoma.setText("=");
        btnSoma.addActionListener(this::btnSomaActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(btnSoma, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSoma)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtN1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtN2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSoma)
                    .addComponent(lblSoma))
                .addGap(78, 78, 78))
        );

        pack();
    }// </editor-fold>                        

    private void btnSomaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int n1 = Integer.parseInt(txtN1.getText()), n2 = Integer.parseInt(txtN2.getText());
        
        int s = n1 + n2;
        
        lblSoma.setText(Integer.toString(s));
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AulaPratica06().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnSoma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSoma;
    private javax.swing.JTextField txtN1;
    private javax.swing.JTextField txtN2;
    // End of variables declaration                   
}