// Estruturas condicionais parte 2
package Curso_Guanabara.Exercicies;
// @author Cauã Sousa
import java.util.Scanner;
import javax.swing.DefaultListModel;
public class Aula13 {
    public static void main(String[] args) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        Scanner Exercicio13 = new Scanner(System.in);
        Exercicies13.executar(Exercicio13);

        ExerciciesPratics13 tela1 = new ExerciciesPratics13();
        tela1.setVisible(true);
        Exercicio13.close();
    }
}
class Exercicies13 {
    public static void executar(Scanner Exercicio13) {
        System.out.println("01. Considerando o trecho de Fluxograma representado e mantendo a mesma estrutura de lógica de " +
        "programação, qual seria a sua transcrição válida para Linguagem Java?\n");

        System.out.println("Imagem na pasta Prints!\n");

        System.out.println("a. for(int c=0; c<=10; c+=2) {");
        System.out.println("       s+=c;");
        System.out.println("   }");

        System.out.println("b. for(int c=0; c<10; c+=2) {");
        System.out.println("       s+=c;");
        System.out.println("   }");

        System.out.println("c. for(int c=0; c<=10; c++) {");
        System.out.println("       s+=c;");
        System.out.println("   }");

        System.out.println("d. for(int c=0; c>=10; c++) {");
        System.out.println("       s+=c;");
        System.out.println("   }");

        String RespostaScann01 = Exercicio13.nextLine();
        System.out.println();

        boolean Resposta01 = RespostaScann01.equals("a");

        if (Resposta01 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: a");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio13.nextLine();

        // NEXT

        System.out.println("02. Qual dos códigos abaixo vai efetuar uma iteração com exatamente 10 laços utilizando uma " +
        "estrutura de repetição com variável de controle?\n");

        System.out.println("a. for(int c=1; c<10; c++)");

        System.out.println("b. for(int c=33; c>13; c-=2)");

        System.out.println("c. for(int c=1; c<=10; c--)");

        System.out.println("d. for(int c=13; c<=33; c+=2)");

        String RespostaScann02 = Exercicio13.nextLine();
        System.out.println();

        boolean Resposta02 = RespostaScann02.equals("b");

        if (Resposta02 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: b");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio13.nextLine();

        // NEXT

        System.out.println("03. Qual será o resultado impresso pelo trecho de código escrito em Linguagem Java?\n");

        System.out.println("for (int i=0; i<=15; i+=2) {\n" +
                            "   if (i%3==0) continue;\n" +
                            "   System.out.println(i);\n" +
                            "}\n");

        System.out.println("a. 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15");

        System.out.println("b. 0 2 4 6 8 10 12 14");

        System.out.println("c. 0 2 4 8 10 14");

        System.out.println("d. 2 4 8 10 14");

        String RespostaScann03 = Exercicio13.nextLine();
        System.out.println();

        boolean Resposta03 = RespostaScann03.equals("d");

        if (Resposta03 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: d");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio13.nextLine();
    }
    public static void main(String[] args) {
        Scanner Exercicio13 = new Scanner(System.in);
        Exercicies13.executar(Exercicio13);
    }
}
class ExerciciesPratics13 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExerciciesPratics13.class.getName());

    /**
     * Creates new form ExerciciesPratics13
     */
    public ExerciciesPratics13() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sliderInicio = new javax.swing.JSlider();
        sliderFim = new javax.swing.JSlider();
        sliderPasso = new javax.swing.JSlider();
        lblInicio = new javax.swing.JLabel();
        lblFim = new javax.swing.JLabel();
        lblPasso = new javax.swing.JLabel();
        btnCont = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCont = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inicio");

        jLabel2.setText("Fim");

        jLabel3.setText("Passo");

        sliderInicio.setMaximum(5);
        sliderInicio.setValue(0);
        sliderInicio.addChangeListener(this::sliderInicioStateChanged);

        sliderFim.setMaximum(20);
        sliderFim.setMinimum(6);
        sliderFim.setValue(6);
        sliderFim.addChangeListener(this::sliderFimStateChanged);

        sliderPasso.setMaximum(4);
        sliderPasso.setMinimum(1);
        sliderPasso.setValue(1);
        sliderPasso.addChangeListener(this::sliderPassoStateChanged);

        lblInicio.setText("0");

        lblFim.setText("6");

        lblPasso.setText("1");

        btnCont.setText("Contar");
        btnCont.addActionListener(this::btnContActionPerformed);

        jScrollPane1.setViewportView(lstCont);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(sliderInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblPasso, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                    .addComponent(lblFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCont, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(85, 85, 85))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sliderInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(lblInicio))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(sliderFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFim))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sliderPasso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPasso))
                .addGap(18, 18, 18)
                .addComponent(btnCont)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void sliderInicioStateChanged(javax.swing.event.ChangeEvent evt) {                                          
        int i = sliderInicio.getValue();
        lblInicio.setText(Integer.toString(i));
    }                                         

    private void sliderFimStateChanged(javax.swing.event.ChangeEvent evt) {                                       
        int f = sliderFim.getValue();
        lblFim.setText(Integer.toString(f));
    }                                      

    private void sliderPassoStateChanged(javax.swing.event.ChangeEvent evt) {                                         
        int p = sliderPasso.getValue();
        lblPasso.setText(Integer.toString(p));
    }                                        

    private void btnContActionPerformed(java.awt.event.ActionEvent evt) {                                        
        int i, f, p;
        i = sliderInicio.getValue(); f = sliderFim.getValue(); p = sliderPasso.getValue();

        DefaultListModel<Integer> lista = new DefaultListModel<>();

        for (int c = i; c <= f; c += p) {
            lista.addElement(c);
        }

        lstCont.setModel(lista);
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExerciciesPratics13().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCont;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFim;
    private javax.swing.JLabel lblInicio;
    private javax.swing.JLabel lblPasso;
    private javax.swing.JList<Integer> lstCont;
    private javax.swing.JSlider sliderFim;
    private javax.swing.JSlider sliderInicio;
    private javax.swing.JSlider sliderPasso;
    // End of variables declaration                   
}