// Introdução ao Swing e JavaFX
package Curso_Guanabara.Exercicies;
// @author Cauã Sousa
import java.util.Scanner;
import java.util.Date;
import java.util.Locale;
import java.awt.Dimension;
import java.awt.Toolkit;
public class Aula05 {
    public static void main(String[] args) {
        Scanner Exercicio05 = new Scanner(System.in);
        Exercicies05.executar(Exercicio05); // Primeiro roda perguntas no terminal
        ExerciciesPratics05.main(args); // Depois abre a janela Swing
        Exercicio05.close();
    }
}
class Exercicies05 {
    @SuppressWarnings("ConvertToTryWithResources")
    public static void executar(Scanner Exercicio05) {
        System.out.println("(CAP-PD) - 01. Segundo a linguagem de programação Java"
        + ", assinale a opção incorreta.");

        System.out.println("a. O Java diferencia letras maiúsculas de minúsculas.");
        System.out.println("b. A palavra-chave \"new\" introduz uma declaração de classe"
        + " e é imediatamente seguida pelo nome da classe.");
        System.out.println("c. O método \"main\" é o ponto de partida de cada aplicativo"
        + " Java e deve iniciar com \"public static void main(String[] args)\".");
        System.out.println("d. O corpo de cada declaração de classe é delimitado por chaves.");
        System.out.println("e. Cada instrução termina com ponto e virgula.");

        String RespostaScann01 = Exercicio05.nextLine();
        System.out.println();

        boolean Resposta01 = RespostaScann01.equals("b");

        if (Resposta01 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: b");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio05.nextLine();

        System.out.println("(CAP-PD) - 02. Uma pilha é uma versão limitada de uma lista"
        + " encadeada. Novos nós só podem ser adicionados e retirados de uma pilha pelo"
        + " topo. Em Java, a classe Stack possui métodos de manipulação em pilhas. Em"
        + " qual pacote a classe Stack está definida?");

        System.out.println("a. java.util");
        System.out.println("b. java.lang");
        System.out.println("c. java.net");
        System.out.println("d. java.io");
        System.out.println("e. java.swt");

        String RespostaScann02 = Exercicio05.nextLine();
        System.out.println();

        boolean Resposta02 = RespostaScann02.equals("a");

        if (Resposta02 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: a");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio05.nextLine();

        System.out.println("(CAP-PD) - 03. Na linguagem de programação JAVA, que palavra-chave"
        + " cria um objeto de uma classe espcifica?");

        System.out.println("a. main");
        System.out.println("b. public");
        System.out.println("c. class");
        System.out.println("d. private");
        System.out.println("e. new");

        String RespostaScann03 = Exercicio05.nextLine();
        System.out.println();

        boolean Resposta03 = RespostaScann03.equals("e");

        if (Resposta03 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: e");
        }
        System.out.println("Fim das Questões, aperte ENTER para Exercicios Praticos.");
        Exercicio05.nextLine();
        Exercicio05.close();
    }
    public static void main(String[] args) {
        Scanner Exercicio05 = new Scanner(System.in);
        Exercicies05.executar(Exercicio05);
        Exercicio05.close();
    }
}
class ExerciciesPratics05 extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExerciciesPratics05.class.getName());
    public ExerciciesPratics05() {
        initComponents();
    }
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("Convert2Lambda")
    private void initComponents() {
        lblCalendarIcon = new javax.swing.JLabel();
        lblTitleDtHr = new javax.swing.JLabel();
        lblDtHr = new javax.swing.JLabel();
        btnRevelarDtHr = new javax.swing.JButton();
        lblGlobeIcon = new javax.swing.JLabel();
        lblTitleGlobe = new javax.swing.JLabel();
        lblGlobe = new javax.swing.JLabel();
        btnRevelarGlobe = new javax.swing.JButton();
        lblDisplayIcon = new javax.swing.JLabel();
        lblTitleDisplay = new javax.swing.JLabel();
        lblDisplay = new javax.swing.JLabel();
        btnRevelarDisplay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCalendarIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Curso_Guanabara/Exercicies/Imagens/Calendar.png"))); // NOI18N

        lblTitleDtHr.setText("Data e Hora do Sistema");

        lblDtHr.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblDtHr.setForeground(new java.awt.Color(102, 102, 102));
        lblDtHr.setText("Clique no Botão");

        btnRevelarDtHr.setText("Revelar");
        btnRevelarDtHr.addActionListener(new java.awt.event.ActionListener() {
            @SuppressWarnings("override")
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevelarDtHrActionPerformed(evt);
            }
        });

        lblGlobeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Curso_Guanabara/Exercicies/Imagens/Globe.png"))); // NOI18N

        lblTitleGlobe.setText("Linguagem do Sistema");

        lblGlobe.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblGlobe.setForeground(new java.awt.Color(102, 102, 102));
        lblGlobe.setText("Clique no Botão");

        btnRevelarGlobe.setText("Revelar");
        btnRevelarGlobe.addActionListener(new java.awt.event.ActionListener() {
            @SuppressWarnings("override")
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevelarGlobeActionPerformed(evt);
            }
        });

        lblDisplayIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Curso_Guanabara/Exercicies/Imagens/Monitor.png"))); // NOI18N

        lblTitleDisplay.setText("Display do Sistema");

        lblDisplay.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        lblDisplay.setForeground(new java.awt.Color(102, 102, 102));
        lblDisplay.setText("Clique no Botão");

        btnRevelarDisplay.setText("Revelar");
        btnRevelarDisplay.addActionListener(new java.awt.event.ActionListener() {
            @SuppressWarnings("override")
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRevelarDisplayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblCalendarIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTitleDtHr)
                                                        .addComponent(lblDtHr)
                                                        .addComponent(btnRevelarDtHr)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblGlobeIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTitleGlobe)
                                                        .addComponent(lblGlobe)
                                                        .addComponent(btnRevelarGlobe)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblDisplayIcon)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(lblTitleDisplay)
                                                        .addComponent(lblDisplay)
                                                        .addComponent(btnRevelarDisplay))))
                                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(lblCalendarIcon))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(19, 19, 19)
                                                .addComponent(lblTitleDtHr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDtHr)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnRevelarDtHr)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(lblGlobeIcon)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(lblTitleGlobe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblGlobe)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnRevelarGlobe)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblDisplayIcon))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addComponent(lblTitleDisplay)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lblDisplay)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnRevelarDisplay)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnRevelarDtHrActionPerformed(java.awt.event.ActionEvent evt) {
        Date relogio = new Date();
        lblDtHr.setText(relogio.toString());
    }

    private void btnRevelarGlobeActionPerformed(java.awt.event.ActionEvent evt) {
        Locale Brasil = Locale.getDefault();
        lblGlobe.setText(Brasil.getDisplayLanguage());
    }

    private void btnRevelarDisplayActionPerformed(java.awt.event.ActionEvent evt) {
        Toolkit resolucaoTela = Toolkit.getDefaultToolkit();
        // Obtém o tamanho da tela e retorna um objeto Dimension
        Dimension dimensaoTela = resolucaoTela.getScreenSize();
        // Obtém a largura e a altura do objeto Dimension
        int largura = dimensaoTela.width;
        int altura = dimensaoTela.height;
        lblDisplay.setText(largura + " x " + altura);
    }
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExerciciesPratics05().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnRevelarDisplay;
    private javax.swing.JButton btnRevelarDtHr;
    private javax.swing.JButton btnRevelarGlobe;
    private javax.swing.JLabel lblCalendarIcon;
    private javax.swing.JLabel lblDisplay;
    private javax.swing.JLabel lblDisplayIcon;
    private javax.swing.JLabel lblDtHr;
    private javax.swing.JLabel lblGlobe;
    private javax.swing.JLabel lblGlobeIcon;
    private javax.swing.JLabel lblTitleDisplay;
    private javax.swing.JLabel lblTitleDtHr;
    private javax.swing.JLabel lblTitleGlobe;
    // End of variables declaration                   
}