// Operadores aritméticos
package Curso_Guanabara.Exercicies;
// @author Cauã Sousa
import java.util.Scanner;
import java.awt.Font;
public class Aula08 {
    public static void main(String[] args) {
        Scanner Exercicio08 = new Scanner(System.in);
        Exercicies08.executar(Exercicio08);
        ExerciciesPratics08.main(args);
        Exercicio08.close();
    }
}
class Exercicies08 {
    public static void executar(Scanner Exercicio08) {
        System.out.println("01. Dadas as linhas a seguir:");

        System.out.println();

        System.out.println("int x = 8, y = 3;");
        System.out.println("int w = x / y;");
        System.out.println("String z = (w % 2 == 0)?\"Frase1\":\"Frase2\";");
        System.out.println("System.out.println(z);");

        System.out.println();

        System.out.println("O que acontecerá se esse código for executado?");

        System.out.println("a. Um erro de tipo na variável w");
        System.out.println("b. Um erro de atribuição na variável z");
        System.out.println("c. Será impresso a Frase1");
        System.out.println("d. Será impresso a Frase2");

        String RespostaScann01 = Exercicio08.nextLine();
        System.out.println();

        boolean Resposta01 = RespostaScann01.equals("c");

        if (Resposta01 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: c");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio08.nextLine();

        // NEXT

        System.out.println("02. Analise o código a seguir e indique o que será impresso na tela:");

        System.out.println();

        System.out.println("String parte1 = \"Curso\";");
        System.out.println("String parte2 = \"Video\";");
        System.out.println("String parte3 = parte1 + parte2;");
        System.out.println("String parte4 = \"CursoVideo\";");
        System.out.println("System.out.println(parte3 == parte4);");
        System.out.println("System.out.println(parte3.equals(parte4));");

        System.out.println();

        System.out.println("a. CursoVideo");
        System.out.println("b. false true");
        System.out.println("c. true true");
        System.out.println("d. true false");

        String RespostaScann02 = Exercicio08.nextLine();
        System.out.println();

        boolean Resposta02 = RespostaScann02.equals("b");

        if (Resposta02 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: b");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio08.nextLine();

        // NEXT

        System.out.println("03. Analise o código a seguir e indique o que será impresso na tela:");

        System.out.println();

        System.out.println("boolean val1 = (4>=5), val2 = (4<4), val3 = (val1 == val2);");
        System.out.println("boolean val 4 = val1 ^ val3;");
        System.out.println("boolean val 5 = !val2 && val4;");
        System.out.println("System.out.println(val4 + \" \" + val5);");

        System.out.println();

        System.out.println("a. true true");
        System.out.println("b. false true");
        System.out.println("c. false false");
        System.out.println("d. true false");

        String RespostaScann03 = Exercicio08.nextLine();
        System.out.println();

        boolean Resposta03 = RespostaScann03.equals("a");

        if (Resposta03 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: a");
        }

        System.out.println("Fim das Questões, aperte ENTER para Exercicios Praticos.");
        Exercicio08.nextLine();
        Exercicio08.close();
    }
    public static void main(String[] args) {
        Scanner Exercicio08 = new Scanner(System.in);
        Exercicies08.executar(Exercicio08);
        Exercicio08.close();
    }
}
class ExerciciesPratics08 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExerciciesPratics08.class.getName());

    /**
     * Creates new form ExerciciesPratics08
     */
    public ExerciciesPratics08() {
        initComponents();
        lblFrase.setText("<html>Vou pensar em um número de <strong>1 à 5</strong>. Tente adivinhar o número que eu pensar</html>");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblFrase = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnPalpite = new javax.swing.JButton();
        spinVal = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Curso_Guanabara/Exercicies/Imagens/Genio.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lblFrase.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        lblFrase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFrase.setText("Frase");
        lblFrase.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(lblFrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 140, 90));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Curso_Guanabara/Exercicies/Imagens/balao.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("Valor");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, -1, -1));

        btnPalpite.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        btnPalpite.setText("Palpite");
        btnPalpite.addActionListener(this::btnPalpiteActionPerformed);
        getContentPane().add(btnPalpite, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 130, -1));

        spinVal.setModel(new javax.swing.SpinnerNumberModel(1, 1, 5, 1));
        getContentPane().add(spinVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 80, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("MINI GAME!!");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, -1, -1));

        pack();
    }// </editor-fold>                        

    private void btnPalpiteActionPerformed(java.awt.event.ActionEvent evt) {                                           
        double n = 1 + Math.random() * (6 - 1);
        int valor = (int) n;

        int num = Integer.parseInt(spinVal.getValue().toString());

        String f1 = "<html>ACERTOU!</html>";
        String f2 = "<html>ERROU! Pensei no número " + valor + "</html>";

        String res = (valor == num)?f1:f2;

        lblFrase.setFont(new Font("Arial Black", Font.PLAIN, 16));
        lblFrase.setText(res);
    }                                          

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExerciciesPratics08().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnPalpite;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblFrase;
    private javax.swing.JSpinner spinVal;
    // End of variables declaration                   
}