// Operadores aritméticos
package Curso_Guanabara.Exercicies;
// @author Cauã Sousa
import java.util.Scanner;
public class Aula07 {
    public static void main(String[] args) {
        Scanner Exercicio07 = new Scanner(System.in);
        Exercicies07.executar(Exercicio07);
        ExerciciesPratics07.main(args);
        Exercicio07.close();
    }
}
class Exercicies07 {
    public static void executar(Scanner Exercicio07) {
        System.out.println("01. Considerando o trecho de código a seguir, construído na linguagem Java, marque a opção que "
        + "preencha as lacunas");

        System.out.println();

        System.out.println("int n = 4;");
        System.out.println("System.out.println(\"O valor da variavel é \" + n++);");

        System.out.println();

        System.out.println("Executando as linhas acima, será exibida a mensagem \"O valor da variavel é ___\" e o "
        + "valor final de n após a execução final será ___.");

        System.out.println("a. 3 e 4.");
        System.out.println("b. 4 e 5.");
        System.out.println("c. 5 e 5.");
        System.out.println("d. 3 e 3.");

        String RespostaScann01 = Exercicio07.nextLine();
        System.out.println();

        boolean Resposta01 = RespostaScann01.equals("b");

        if (Resposta01 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: b");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio07.nextLine();

        // O java só conta o ++ depois do print, sendo assim, o print sai sem o ++ (4) e depois o valor se torna 5
        // NEXT

        System.out.println("02. Considerando o tratamento de tipos primitivos pelo JAVA, analise o código a seguir e "
        + "indique que valor será impresso na tela:");

        System.out.println();

        System.out.println("int n1 = 2, n2 = 5;");
        System.out.println("double resultado = n2/n1");
        System.out.println("System.out.println(resultado);");

        System.out.println();

        System.out.println("a. 5.0");
        System.out.println("b. 2.0");
        System.out.println("c. 2.5");
        System.out.println("d. 3.0");

        String RespostaScann02 = Exercicio07.nextLine();
        System.out.println();

        boolean Resposta02 = RespostaScann02.equals("b");

        if (Resposta02 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: b");
        }
        System.out.println("Aperte ENTER para continuar");
        Exercicio07.nextLine();

        // n1 e n2 são int, então o resultado será int e não double e nem float, logo 2.5 se torna apenas 2.0
        // NEXT

        System.out.println("03. Execute as três instruções JAVA a seguir e marque a opção que contém o valor que será "
        + "impresso na tela");

        System.out.println();

        System.out.println("int v1 = 7, v2 = v1 % 2, v3 = 2;");
        System.out.println("v3 += v2;");
        System.out.println("System.out.println(v1 + \" \" + v2 + \" \" + v3);");

        System.out.println();

        System.out.println("a. 7 2 4");
        System.out.println("b. 7 1 1");
        System.out.println("c. 7 1 3");
        System.out.println("d. 7 0 2");

        String RespostaScann03 = Exercicio07.nextLine();
        System.out.println();

        boolean Resposta03 = RespostaScann03.equals("c");

        if (Resposta03 == true) {
            System.out.println("Certa Resposta!");
        } else {
            System.out.println("A Resposta correta era: c");
        }

        // v3 += v2 significa que teremos o valor de v3 + o valor de v2

        System.out.println("Fim das Questões, aperte ENTER para Exercicios Praticos.");
        Exercicio07.nextLine();
        Exercicio07.close();
    }
    public static void main(String[] args) {
        Scanner Exercicio07 = new Scanner(System.in);
        Exercicies07.executar(Exercicio07);
        Exercicio07.close();
    }
}

class ExerciciesPratics07 extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ExerciciesPratics07.class.getName());

    /** Creates new form ExerciciesPratics07 */
    public ExerciciesPratics07() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        spinNum = new javax.swing.JSpinner();
        btnCalc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtPor2 = new javax.swing.JLabel();
        txtAoCubo = new javax.swing.JLabel();
        txtRaiz = new javax.swing.JLabel();
        txtRaizCubo = new javax.swing.JLabel();
        txtAbsoluto = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SUPER CALCULADORA");

        jLabel2.setText("Informe um valor");

        spinNum.setModel(new javax.swing.SpinnerNumberModel(0.0d, null, null, 1.0d));

        btnCalc.setText("Calcular");
        btnCalc.addActionListener(this::btnCalcActionPerformed);

        jLabel3.setText("Divisão por 2");

        jLabel4.setText("Elevado ao Cubo");

        jLabel5.setText("Raiz Quadrada");

        jLabel6.setText("Raiz Cubica");

        jLabel7.setText("Valor Absoluto");

        txtPor2.setText("0");

        txtAoCubo.setText("0");

        txtRaiz.setText("0");

        txtRaizCubo.setText("0");

        txtAbsoluto.setText("0");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Curso_Guanabara/Exercicies/Imagens/imgCalc.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAoCubo)
                            .addComponent(txtPor2)
                            .addComponent(txtRaiz)
                            .addComponent(txtRaizCubo)
                            .addComponent(txtAbsoluto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(25, 25, 25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(55, 55, 55)
                        .addComponent(spinNum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(btnCalc)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spinNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalc))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPor2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtAoCubo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtRaiz))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtRaizCubo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtAbsoluto))
                        .addGap(72, 72, 72))))
        );

        pack();
    }// </editor-fold>                        

    private void btnCalcActionPerformed(java.awt.event.ActionEvent evt) {                                        
        double numb = Double.parseDouble(spinNum.getValue().toString());
        double divisao = numb / 2;
        double cubo = Math.pow(numb, 3);
        double raiz = Math.sqrt(numb);
        double raizCub = Math.cbrt(numb);
        double absoluto = Math.abs(numb);
        
        txtAoCubo.setText(String.format("%.2f", cubo));
        txtPor2.setText(String.format("%.2f", divisao));
        txtRaiz.setText(String.format("%.2f", raiz));
        txtRaizCubo.setText(String.format("%.2f", raizCub));
        txtAbsoluto.setText(String.format("%.2f", absoluto));
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ExerciciesPratics07().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCalc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSpinner spinNum;
    private javax.swing.JLabel txtAbsoluto;
    private javax.swing.JLabel txtAoCubo;
    private javax.swing.JLabel txtPor2;
    private javax.swing.JLabel txtRaiz;
    private javax.swing.JLabel txtRaizCubo;
    // End of variables declaration                   

}